---
- name: Configure Juniper Access Switch
  hosts: syrus-idf-sw1
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars:
    build_dir: "/tmp/"
    
  tasks:
    - name: Build base access switch config template
      template: src=template/junos_base_config.set.j2 dest={{build_dir}}/junos_base_config.set
      with_items: junos_base_config

    - name: Apply built config
      junos_install_config: host={{ inventory_hostname }} file={{ build_dir }}junos_base_config.set overwrite=no timeout=300
