- hosts: localhost
  connection: local
  tasks:
    - name: Create security group
      ec2_group:
          name: "TEST
          description: "This is the First test""
          region: "us-east-1"
          vpc_id: "vpc-347f5d4f"
          rules:
              - proto: tcp
                from_port: 22
                to_port: 22
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                from_port: 80
                to_port: 80
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                from_port: 443
                to_port: 443
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                from_port: 4443
                to_port: 4443
                cidr_ip: 0.0.0.0/0
      register: basic_firewall
