---
- hosts: localhost
  connection: local
  tasks:
    - name: Create security group
      ec2_group:
          description: "default VPC security group"
          region: "us-east-1"
          vpc_id: "vpc-347f5d4f"
          name: "default"
          rules:
              - proto: tcp
                from_port: 22
                to_port: 22
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                from_port: 80
                to_port: 80
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                from_port: 4431
                to_port: 4431
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                from_port: 4443
                to_port: 4443
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                from_port: 67
                to_port: 67
                cidr_ip: 10.0.0.0/8
              - proto: tcp
                from_port: 69
                to_port: 69
                cidr_ip: 10.0.0.0/8

      register: basic_firewall
