---
- hosts: localhost
  connection: local
  tasks:
    - name: Create security group
      ec2_group:
          name: "{{ project_name }}"
          description: "default VPC security group"
          region: "us-east-1"
          rules:
              - proto: tcp
                from_port: 22
                to_port: 22
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                from_port: 80
                to_port: 80
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                from_port: 443
                to_port: 443
                cidr_ip: 0.0.0.0/0
                group_id: sg-043939aa054287c9c
      register: basic_firewall
