---
- hosts: localhost
  connection: local

  roles:
    - role: paloaltonetworks.paloaltonetworks
    
  tasks:

    - name: Address Object
      panos_address_object:
        ip_address: "{{ ip_address }}"
        username: "{{ username }}"
        password: "{{ password }}"
        devicegroup: "{{ device_group }}"
        name: "{{ source_name }}"
        value: "{{ source_ip }}"
        commit: False
      tags:
        - AddressObject
        
    - name: Security Rule
      panos_security_rule:
        operation: 'add'
        ip_address: "{{ ip_address }}"
        username: "{{ username }}"
        password: "{{ password }}"
        devicegroup: "{{ device_group }}"
        rulebase: "{{ rulebase }}"
        rule_name: "{{ rule_name }}"
        source_zone: "{{ source_zone }}"
        source_ip: "{{ source_names }}"
        destination_zone: "{{ destination_zone }}"
        destination_ip: "{{ destination_ip }}"
        application: "{{ application }}"
        service: "{{ service }}"
        action: 'allow'
        #log_setting: "LFP-POLICY1"
        #group_profile: "SPG-Default" #IDP, Actions, Profile Setting
        commit: False
      tags:
        - SecurityRule
