---
- name: My System | Provision all required infrastructure
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create new customer gateway
      ec2_customer_gateway:
        bgp_asn: 65300
        ip_address: 73.167.85.18
        name: SYRUS-MDF-FW1
        region: us-east-1
      register: customer_gateway_id

    - debug: 
        var: customer_gateway_id
        
#    - name: Create new VGW attached to VPC
#      ec2_vpc_vgw:
#        state: present
#        region: us-east-1
#        #profile: personal
#        vpc_id: "{{ vpc_id }}"
#        name: personal-testing
#        type: ipsec.1
#      register: created_vgw
#      
#    - name: VGW Facts
#      ec2_vpc_vgw_facts:
#        vpc_id: "{{ vpc_id }}"
#        region: us-east-1
#      register: virtual_gateways   
#
#    - name: Create VPN
#      ec2_vpc_vpn:
#        state: present
#        region: us-east-1
#        vpn_gateway_id: "{{ id }}"
#        customer_gateway_id: "{{ customer_gateway_id }}"

