---
- name: My System | Provision all required infrastructure
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create new customer gateway
      ec2_vpc_vpn:
        state: present
        region: "{{ aws_region }}"
        vpn_gateway_id: "{{ vgw_id }}"
        customer_gateway_id: "{{ cgw_id }}"
        tunnel_options:
          -
            TunnelInsideCidr: '169.254.100.1/30'
          -
            TunnelInsideCidr: '169.254.100.5/30'
        

      register: outside_ip_address

    - debug: var=outside_ip_address
