---
- hosts: localhost
  connection: local

  tasks:
    - name: Create Palo SNMP configuration
      command: panxapi.py -h {{ panorama }} -e /{{build_dir}}/palo_snmp.xml -K "{{palo_api}}" /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='{{template}}']/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/snmp-setting
      tags: 
        - palo_snmp
