---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a VPC across two Avalibity Zones with Public and Private subnets 
      cloudformation:
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key:	'{{ aws_secret_key }}'
        state: "present"
        region: "us-east-1"
        disable_rollback: true
        template: "vpc/CF-PPR-2AZ-VPC.yml"
        tags:
          Stack: stack_name
