---
- name: Configure Juniper Access Switch
  hosts: 2300c
  connection: local
  gather_facts: no
  roles:
    - juniper.junos
    
  vars:
    - build_dir: '/tmp/'
      mgmt_ip: "192.168.1.15"
    - system_vars:
        - city_code: "MIA8400"
          closet: "MDF"
          type: "ASW1"
          mgmt_ip: "{{mgmt_ip}}"
          acs_secret: '1234'
    - snmp_vars:    
        - address: 'Milford 325'
          username: "{{snmp_username}}'
          auth_password: '{{priv_password}}'
          priv_password: '{{auth_password}}'
    - int_vars:     
        - port_count: 12
          switch_count: 1
          mgmt_ip: "{{mgmt_ip}}"
    - uplink_vars:
        - uplink_int: 'ge-0/0/0'
          description: "MFD325-MDF-CSW1 Port c8"
    - mstp_vars:
        - mstp_name: 'acme'


  tasks:

    - name: Build JunOS System config
      template: src=Template/ex-system.set.j2 dest={{build_dir}}/ex-system.set
      with_items: system_vars
      tags:
        - system

    - name: Apply System config
      junos_install_config: host={{ inventory_hostname }} file={{ build_dir }}ex-system.set overwrite=no timeout=300
      tags:
        - system

    - name: Build JunOS SNMP config
      template: src=Template/juniper_snmp.set.j2 dest={{build_dir}}/juniper_snmp.set
      with_items: snmp_vars
      tags:
        - snmp

    - name: Apply SNMP config
      junos_install_config: host={{ inventory_hostname }} file={{ build_dir }}juniper_snmp.set overwrite=no timeout=300
      tags:
        - snmp
        
    - name: Build Access switch Interface configuration
      template: src=Template/access-interfaces.set.j2 dest={{build_dir}}/access-interfaces.set
      with_items: int_vars
      tags:
        - interface

    - name: Apply interface config
      junos_install_config: host={{ inventory_hostname }} file={{ build_dir }}access-interfaces.set overwrite=no timeout=300
      tags:
        - interface

    - name: Build Uplink Interface configuration
      template: src=Template/uplink-interfaces.set.j2 dest={{build_dir}}/uplink-interfaces.set
      with_items: uplink_vars
      tags:
        - uplink

    - name: Apply interface config
      junos_install_config: host={{ inventory_hostname }} file={{ build_dir }}uplink-interfaces.set overwrite=no timeout=300
      tags:
        - uplink
        
    - name: Build mstp configuration
      template: src=Template/mstp.set.j2 dest={{build_dir}}/mstp.set
      with_items: mstp_vars
      tags:
        - mstp

    - name: Apply mstp config
      junos_install_config: host={{ inventory_hostname }} file={{ build_dir }}mstp.set overwrite=no timeout=300
      tags:
        - mstp       
 
    - name: Build JunOS filter config
      template: src=Template/filter.set.j2 dest={{build_dir}}/filter.set
      with_items: system_vars
      tags:
        - filter

    - name: Apply filter config
      junos_install_config: host={{ inventory_hostname }} file={{ build_dir }}filter.set overwrite=no timeout=300
      tags:
        - filter
