---
- name: Configure Juniper Access Switch
  hosts: 2300c
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
    
  vars:
    - build_dir: '/tmp/'
    - system_vars:
        - city_code: "MIA8400"
          closet: "MDF"
          type: "ASW1"
          mgmt_ip: "192.168.1.15"
          acs_secret: '1234'
    - snmp_vars:    
        - address: 'Milford 325'
          username: 'SW-MFD325-RO'
          auth_password: '1234567890'
          priv_password: '0987654321'
    - int_vars:     
        - port_count: 12
          switch_count: 1
    - uplink_vars:
        - uplink_int: 'ge-0/0/0'
    - mstp_vars:    


  tasks:

    - name: Build JunOS System config
      template: src=Template/ex-system.set.j2 dest={{build_dir}}/ex-system.set
      with_items: system_vars
      tags:
        - system

    - name: Apply System config
      junos_install_config: host={{ inventory_hostname }} file={{ build_dir }}ex-system.set overwrite=no timeout=300
      tags:
        - system

    - name: Build JunOS SNMP config
      template: src=Template/juniper_snmp.set.j2 dest={{build_dir}}/juniper_snmp.set
      with_items: snmp_vars
      tags:
        - snmp

    - name: Apply SNMP config
      junos_install_config: host={{ inventory_hostname }} file={{ build_dir }}juniper_snmp.set overwrite=no timeout=300
      tags:
        - snmp
        
    - name: Build Access switch Interface configuration
      template: src=Template/access-interfaces.set.j2 dest={{build_dir}}/access-interfaces.set
      with_items: int_vars
      tags:
        - interface

    - name: Apply interface config
      junos_install_config: host={{ inventory_hostname }} file={{ build_dir }}access-interfaces.set overwrite=no timeout=300
      tags:
        - interface

    - name: Build Uplink Interface configuration
      template: src=Template/uplink-interfaces.set.j2 dest={{build_dir}}/uplink-interfaces.set
      with_items: uplink_vars
      tags:
        - uplink

    - name: Apply interface config
      junos_install_config: host={{ inventory_hostname }} file={{ build_dir }}uplink-interfaces.set overwrite=no timeout=300
      tags:
        - uplink
        
    - name: Build mstp configuration
      template: src=Template/mstp.set.j2 dest={{build_dir}}/mstp.set
      with_items: mstp_vars
      tags:
        - mstp

    - name: Apply mstp config
      junos_install_config: host={{ inventory_hostname }} file={{ build_dir }}mstp.set overwrite=no timeout=300
      tags:
        - mstp       
        
    # If you require access switch configuration for an Airtame network uncomment the next two stanzas
    #- name: Build Airtame Configuration for access switch configuration
    #  template: src=template/access-sw/junos_access_sw_config.set.j2 dest={{build_dir}}/junos_access_sw_config.set
    #  with_items: junos_access_sw_config

    # If you require a L2 Segment for a SIP VRF uncomment the next two stanzas.
    #- name: Build MPLS SIP L2 confiugration
    #  template: src=template/junos_mpls-sip_config.set.j2 dest={{build_dir}}/junos_mpls_sip_config.set

    #- name: Build phpIPAM address reservation
    #  template: src=template/phpipam_config.j2 dest={{build_dir}}/phpipam_config.text
    #  with_items: phpipam_config
