---
- name: Configure Juniper SNMP
  connection: local
  hosts: syrus-mdf-fw1
  gather_facts: no
  #roles:
  #  - juniper.junos

  vars:
    build_dir: "/tmp/"
    junos_snmp_config:
      - address: 'Test'
        city_code: 'MIA'
        auth_password: '{{ auth_password }}'
        priv_password: '{{ priv_password }}'

  tasks:
    - name: Build JunOS Switch SNMP Configuration
      template: src=Template/juniper_snmp.set.j2 dest={{build_dir}}/junos_switch_snmp_config.set
      with_items: junos_snmp_config

    - name: Read App Version
      command: cat {{ build_dir }}/junos_switch_snmp_config.set
      register: app_version

    - name: display set commands
      debug:
        msg: "App Version {{ app_version.stdout }}"

